version: '3'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ../.env
    ports:
      - 5432:5432

  # app:
  #   build: .
  #   restart: always
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - ../.env
  #   volumes:
  #     - esp-files:../app/files
# volumes:
#   esp-files:
#     name: esp-files
